#statistical functions
import numpy as np
array1=np.array([1,2,3,4,5])
print("Array:",array1)
print("Mean:",np.mean(array1))
print("Medain:",np.medain(array1))
print("Mode:",np.bicount(array1).argmax())
print("Maximum:",np.max(array1))
print("Minimum:",np.min(array1))
print("Range:",np.ptp(array1))
print("Sum:",np.sum(array1))
print("Product:",np.prod(array1))
print("Variance:",np.var(array1))
print("Satandard deviation:",np.std(array1))
print("25th percentile(q1):",np.percentile(array1,25))
print("50th percentile(q2):",np.percentile(array1,50))
print("75th percentile(q3):",np.percentile(array1,75))
print("Cumulative sum:",np.cumsum(array1))
print("Cumulative product:",np.sumprod(array1))