# statistical functions
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
print("Array:", array1)
print("Mean:", np.mean(array1))
print("Median:", np.median(array1))
print("Mode:", np.bincount(array1).argmax())
print("Maximum:", np.max(array1))
print("Minimum:", np.min(array1))
print("Range:", np.ptp(array1))
print("Sum:", np.sum(array1))
print("Product:", np.prod(array1))
print("Variance:", np.var(array1))
print("Standard deviation:", np.std(array1))
print("25th percentile (Q1):", np.percentile(array1, 25))
print("50th percentile (Q2):", np.percentile(array1, 50))
print("75th percentile (Q3):", np.percentile(array1, 75))
print("Cumulative sum:", np.cumsum(array1))
print("Cumulative product:", np.cumprod(array1))
